services:
    nextjs:
        container_name: nextjs
        # Provide ENVs to runtime
        env_file:
            - ./.env.merged
        build:
            context: ./
            # Provide ARGs to buildtime
            args:
                - NODE_ENV=${NODE_ENV}
                - NEXTJS_STANDALONE=${NEXTJS_STANDALONE}
                - DATABASE_URL=${DATABASE_URL}
                - MYSQL_HOST=${MYSQL_HOST}
            dockerfile: ./Dockerfile
            target: runner
        ports:
            - "3000:3000"
        restart: unless-stopped
        # volumes:
        #     - nextjs-volume:/app/.next/cache
        networks:
            - nextjs-network

# volumes:
# nextjs-volume:
#     name: nextjs-volume
#     driver: local

networks:
    nextjs-network:
        driver: bridge
