services:
    nextjs:
        container_name: nextjs-${VPS_SUB_DOMAIN}
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: runner
        restart: unless-stopped
        volumes:
            - nextjs-volume:/app/.next/cache
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextjs-${VPS_SUB_DOMAIN}.rule=Host(`${VPS_SUB_DOMAIN}.${VPS_DOMAIN}`)"
            - "traefik.http.routers.nextjs-${VPS_SUB_DOMAIN}.entrypoints=websecure"
            - "traefik.http.services.nextjs-${VPS_SUB_DOMAIN}.loadbalancer.server.port=${TRAEFIK_NETWORK_FRONT_PORT}"
            - "traefik.http.routers.nextjs-${VPS_SUB_DOMAIN}.tls=true"

volumes:
    nextjs-volume:
        name: nextjs-volume-${VPS_SUB_DOMAIN}
        driver: local

networks:
    traefik:
        external: true
        name: traefik
