import BasketService from "@class/BasketClass";
import { Prisma } from "@prisma/client/client";
import {
    BasketCountProps,
    BasketCountResponse,
    BasketFindFirstProps,
    BasketFindFirstResponse,
    BasketFindManyProps,
    BasketFindManyResponse,
    BasketFindUniqueProps,
    BasketFindUniqueResponse,
} from "@services/types";
import { cacheLife, cacheTag } from "next/cache";
import { cacheLifeApi, hashParamsForCacheKey } from "@/solid/solid-config";

/**
 * # Basket Cached Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/cached/{{model}}Cached.hbs` as base template
 * - to generate cached function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Services ========== //

export const BasketFindFirstCached = async <T extends Prisma.BasketFindFirstArgs>(
    params: BasketFindFirstProps<T>,
): Promise<BasketFindFirstResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All basket services
        "basket",
        // All findFirst services
        "findFirst",
        // All basket findFirst services
        "basket-findFirst",
        // This specific services
        hashParamsForCacheKey("basket-findFirst", params),
    );

    return await BasketService.findFirst(params);
};

export const BasketFindUniqueCached = async <T extends Prisma.BasketFindUniqueArgs>(
    params: BasketFindUniqueProps<T>,
): Promise<BasketFindUniqueResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All basket services
        "basket",
        // All findUnique services
        "findUnique",
        // All basket findUnique services
        "basket-findUnique",
        // This specific services
        hashParamsForCacheKey("basket-findUnique", params),
    );

    return await BasketService.findUnique(params);
};

export const BasketFindManyCached = async <T extends Prisma.BasketFindManyArgs>(
    params: BasketFindManyProps<T>,
): Promise<BasketFindManyResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All basket services
        "basket",
        // All findMany services
        "findMany",
        // All basket findMany services
        "basket-findMany",
        // This specific services
        hashParamsForCacheKey("basket-findMany", params),
    );

    return await BasketService.findMany(params);
};

export const BasketCountCached = async <T extends Prisma.BasketCountArgs>(
    params: BasketCountProps<T>,
): Promise<BasketCountResponse<T>> => {
    "use cache";

    cacheLife(cacheLifeApi);
    cacheTag(
        // All services
        "services",
        // All basket services
        "basket",
        // All count services
        "count",
        // All basket count services
        "basket-count",
        // This specific services
        hashParamsForCacheKey("basket-count", params),
    );

    return await BasketService.count(params);
};
