import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";

/**
 * # Basket Type Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/types/{{model}}Type.hbs` as base template
 * - to generate types files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ============== Utils ============== //

type Payload = Prisma.$BasketPayload<InternalArgs>;

type Flatten<T> = T extends infer U ? { [K in keyof U]: U[K] } : never;

// ============== Model ============== //

/**
 * Basket native fields only
 */
export type BasketModel = Flatten<Payload["scalars"]>;

/**
 * Basket relations fields only
 */
export type BasketRelations = {
    [K in keyof Payload["objects"]]: Payload["objects"][K] extends Array<infer T>
        ? T extends { scalars: unknown }
            ? Flatten<T["scalars"]>[]
            : never
        : Payload["objects"][K] extends { scalars: unknown }
          ? Flatten<Payload["objects"][K]["scalars"]>
          : never;
};

/**
 * Basket native and relations fields
 */
export type BasketComplete = Flatten<BasketModel & BasketRelations>;

/**
 * Basket count type
 */
export type BasketCount = number;

// ========== Types ========== //

/**
 * Basket Create props
 */
export type BasketCreateProps<T extends Prisma.BasketCreateArgs = Prisma.BasketCreateArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketCreateArgs
>;

/**
 * Basket Create response
 */
export type BasketCreateResponse<T extends Prisma.BasketCreateArgs = Prisma.BasketCreateArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

/**
 * Basket Upsert props
 */
export type BasketUpsertProps<T extends Prisma.BasketUpsertArgs = Prisma.BasketUpsertArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketUpsertArgs
>;

/**
 * Basket Upsert response
 */
export type BasketUpsertResponse<T extends Prisma.BasketUpsertArgs = Prisma.BasketUpsertArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

/**
 * Basket Update props
 */
export type BasketUpdateProps<T extends Prisma.BasketUpdateArgs = Prisma.BasketUpdateArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketUpdateArgs
>;

/**
 * Basket Update response
 */
export type BasketUpdateResponse<T extends Prisma.BasketUpdateArgs = Prisma.BasketUpdateArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

/**
 * Basket Delete props
 */
export type BasketDeleteProps<T extends Prisma.BasketDeleteArgs = Prisma.BasketDeleteArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketDeleteArgs
>;

/**
 * Basket Delete response
 */
export type BasketDeleteResponse<T extends Prisma.BasketDeleteArgs = Prisma.BasketDeleteArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

/**
 * Basket Create Many props
 */
export type BasketCreateManyProps<T extends Prisma.BasketCreateManyArgs = Prisma.BasketCreateManyArgs> =
    Prisma.SelectSubset<T, Prisma.BasketCreateManyArgs>;

/**
 * Basket Create Many response
 */
export type BasketCreateManyResponse = Prisma.BatchPayload;

/**
 * Basket Update Many props
 */
export type BasketUpdateManyProps<T extends Prisma.BasketUpdateManyArgs = Prisma.BasketUpdateManyArgs> =
    Prisma.SelectSubset<T, Prisma.BasketUpdateManyArgs>;

/**
 * Basket Update Many response
 */
export type BasketUpdateManyResponse = Prisma.BatchPayload;

/**
 * Basket Delete Many props
 */
export type BasketDeleteManyProps<T extends Prisma.BasketDeleteManyArgs = Prisma.BasketDeleteManyArgs> =
    Prisma.SelectSubset<T, Prisma.BasketDeleteManyArgs>;

/**
 * Basket Delete Many response
 */
export type BasketDeleteManyResponse = Prisma.BatchPayload;

/**
 * Basket Find First props
 */
export type BasketFindFirstProps<T extends Prisma.BasketFindFirstArgs = Prisma.BasketFindFirstArgs> =
    Prisma.SelectSubset<T, Prisma.BasketFindFirstArgs>;

/**
 * Basket Find First response
 */
export type BasketFindFirstResponse<T extends Prisma.BasketFindFirstArgs = Prisma.BasketFindFirstArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

/**
 * Basket Find Unique props
 */
export type BasketFindUniqueProps<T extends Prisma.BasketFindUniqueArgs = Prisma.BasketFindUniqueArgs> =
    Prisma.SelectSubset<T, Prisma.BasketFindUniqueArgs>;

/**
 * Basket Find Unique response
 */
export type BasketFindUniqueResponse<T extends Prisma.BasketFindUniqueArgs = Prisma.BasketFindUniqueArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

/**
 * Basket Find Many props
 */
export type BasketFindManyProps<T extends Prisma.BasketFindManyArgs = Prisma.BasketFindManyArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketFindManyArgs
>;

/**
 * Basket Find Many response
 */
export type BasketFindManyResponse<T extends Prisma.BasketFindManyArgs = Prisma.BasketFindManyArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

/**
 * Basket Count props
 */
export type BasketCountProps<T extends Prisma.BasketCountArgs = Prisma.BasketCountArgs> = Prisma.SelectSubset<
    T,
    Prisma.BasketCountArgs
>;

/**
 * Basket Count response
 */
export type BasketCountResponse<T extends Prisma.BasketCountArgs = Prisma.BasketCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.BasketCountAggregateOutputType>
        : number;
