####################
#   Prisma Studio  #
####################
FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL

COPY package.json bun.lock ./
COPY prisma ./prisma
COPY prisma.config.mts ./prisma.config.mts

RUN bun install --frozen-lockfile
RUN bun run prisma:generate

EXPOSE 5555

CMD ["bun", "run", "prisma:studio", "--port", "5555", "--browser", "none"]
