# .github/actions/setup-node-pnpm/action.yml
name: Setup node, pnpm and dependencies
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v4
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
              version: 10
        - name: Install nodejs
          uses: actions/setup-node@v4
          with:
              node-version: 23
              cache: "pnpm"
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          shell: bash
