import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import {
    BasketCountCached,
    BasketFindFirstCached,
    BasketFindManyCached,
    BasketFindUniqueCached,
} from "@services/cached";

/**
 * # Basket Server Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/server/{{model}}Server.hbs` as base template
 * - to generate server function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type BasketFindFirstProps<T extends Prisma.BasketFindFirstArgs> = Prisma.SelectSubset<T, Prisma.BasketFindFirstArgs>;
type BasketFindFirstResponse<T extends Prisma.BasketFindFirstArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type BasketFindUniqueProps<T extends Prisma.BasketFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.BasketFindUniqueArgs>;
type BasketFindUniqueResponse<T extends Prisma.BasketFindUniqueArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type BasketFindManyProps<T extends Prisma.BasketFindManyArgs> = Prisma.SelectSubset<T, Prisma.BasketFindManyArgs>;
type BasketFindManyResponse<T extends Prisma.BasketFindManyArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type BasketCountProps<T extends Prisma.BasketCountArgs> = Prisma.SelectSubset<T, Prisma.BasketCountArgs>;
type BasketCountResponse<T extends Prisma.BasketCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.BasketCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Basket Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const BasketFindFirstServer = async <T extends Prisma.BasketFindFirstArgs>(
    params: BasketFindFirstProps<T>,
): Promise<BasketFindFirstResponse<T>> => {
    return await BasketFindFirstCached(params);
};

/**
 * ## Basket Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const BasketFindUniqueServer = async <T extends Prisma.BasketFindUniqueArgs>(
    params: BasketFindUniqueProps<T>,
): Promise<BasketFindUniqueResponse<T>> => {
    return await BasketFindUniqueCached(params);
};

/**
 * ## Basket Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const BasketFindManyServer = async <T extends Prisma.BasketFindManyArgs>(
    params: BasketFindManyProps<T>,
): Promise<BasketFindManyResponse<T>> => {
    return await BasketFindManyCached(params);
};

/**
 * ## Basket Find (Server)
 *
 * - SSG compatible
 * - cached function
 *
 * **Note**: function generated from template.
 */
export const BasketCountServer = async <T extends Prisma.BasketCountArgs>(
    params: BasketCountProps<T>,
): Promise<BasketCountResponse<T>> => {
    return await BasketCountCached(params);
};
