"use server";

import FruitService from "@class/FruitClass";
// import { requiresSafeMessage } from "@permissions/requiresSafeMessage";
import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";

/**
 * # Fruit Action Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/actions/{{model}}Action.hbs` as base template
 * - to generate server actions files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Create
type FruitCreateProps<T extends Prisma.FruitCreateArgs> = Prisma.SelectSubset<T, Prisma.FruitCreateArgs>;
type FruitCreateResponse<T extends Prisma.FruitCreateArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "create",
    PrismaClientOptions
>;

// Upsert
type FruitUpsertProps<T extends Prisma.FruitUpsertArgs> = Prisma.SelectSubset<T, Prisma.FruitUpsertArgs>;
type FruitUpsertResponse<T extends Prisma.FruitUpsertArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "upsert",
    PrismaClientOptions
>;

// Update
type FruitUpdateProps<T extends Prisma.FruitUpdateArgs> = Prisma.SelectSubset<T, Prisma.FruitUpdateArgs>;
type FruitUpdateResponse<T extends Prisma.FruitUpdateArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "update",
    PrismaClientOptions
>;

// Delete
type FruitDeleteProps<T extends Prisma.FruitDeleteArgs> = Prisma.SelectSubset<T, Prisma.FruitDeleteArgs>;
type FruitDeleteResponse<T extends Prisma.FruitDeleteArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "delete",
    PrismaClientOptions
>;

// Create Many
type FruitCreateManyProps<T extends Prisma.FruitCreateManyArgs> = Prisma.SelectSubset<T, Prisma.FruitCreateManyArgs>;
type FruitCreateManyResponse = Prisma.BatchPayload;

// Update Many
type FruitUpdateManyProps<T extends Prisma.FruitUpdateManyArgs> = Prisma.SelectSubset<T, Prisma.FruitUpdateManyArgs>;
type FruitUpdateManyResponse = Prisma.BatchPayload;

// Delete Many
type FruitDeleteManyProps<T extends Prisma.FruitDeleteManyArgs> = Prisma.SelectSubset<T, Prisma.FruitDeleteManyArgs>;
type FruitDeleteManyResponse = Prisma.BatchPayload;

// Find First
type FruitFindFirstProps<T extends Prisma.FruitFindFirstArgs> = Prisma.SelectSubset<T, Prisma.FruitFindFirstArgs>;
type FruitFindFirstResponse<T extends Prisma.FruitFindFirstArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type FruitFindUniqueProps<T extends Prisma.FruitFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.FruitFindUniqueArgs>;
type FruitFindUniqueResponse<T extends Prisma.FruitFindUniqueArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type FruitFindManyProps<T extends Prisma.FruitFindManyArgs> = Prisma.SelectSubset<T, Prisma.FruitFindManyArgs>;
type FruitFindManyResponse<T extends Prisma.FruitFindManyArgs> = GetResult<
    Prisma.$FruitPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type FruitCountProps<T extends Prisma.FruitCountArgs> = Prisma.SelectSubset<T, Prisma.FruitCountArgs>;
type FruitCountResponse<T extends Prisma.FruitCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.FruitCountAggregateOutputType>
        : number;

// ========== Services ========== //

/**
 * ## Fruit Create (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitCreateAction = async <T extends Prisma.FruitCreateArgs>(
    props: FruitCreateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitCreateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitCreateAction", "Fruit", "create");
    return await FruitService.create(props);
};

/**
 * ## Fruit Upsert (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitUpsertAction = async <T extends Prisma.FruitUpsertArgs>(
    props: FruitUpsertProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitUpsertResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitUpsertAction", "Fruit", "upsert");
    return await FruitService.upsert(props);
};

/**
 * ## Fruit Update (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitUpdateAction = async <T extends Prisma.FruitUpdateArgs>(
    props: FruitUpdateProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitUpdateResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitUpdateAction", "Fruit", "update");
    return await FruitService.update(props);
};

/**
 * ## Fruit Delete (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitDeleteAction = async <T extends Prisma.FruitDeleteArgs>(
    props: FruitDeleteProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitDeleteResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitDeleteAction", "Fruit", "delete");
    return await FruitService.delete(props);
};

/**
 * ## Fruit Create Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitCreateManyAction = async <T extends Prisma.FruitCreateManyArgs>(
    props: FruitCreateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitCreateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitCreateManyAction", "Fruit", "createMany");
    return await FruitService.createMany(props);
};

/**
 * ## Fruit Update Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitUpdateManyAction = async <T extends Prisma.FruitUpdateManyArgs>(
    props: FruitUpdateManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitUpdateManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitUpdateManyAction", "Fruit", "updateMany");
    return await FruitService.updateMany(props);
};

/**
 * ## Fruit Delete Many (Server Action)
 *
 * - optimized for mutations
 * - serial execution without cache
 *
 * **Note**: function generated from template.
 */
export const FruitDeleteManyAction = async <T extends Prisma.FruitDeleteManyArgs>(
    props: FruitDeleteManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitDeleteManyResponse> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitDeleteManyAction", "Fruit", "deleteMany");
    return await FruitService.deleteMany(props);
};

/**
 * ## Fruit Find First (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const FruitFindFirstAction = async <T extends Prisma.FruitFindFirstArgs>(
    props: FruitFindFirstProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitFindFirstResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitFindFirstAction", "Fruit", "findFirst");
    return await FruitService.findFirst(props);
};

/**
 * ## Fruit Find Unique (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const FruitFindUniqueAction = async <T extends Prisma.FruitFindUniqueArgs>(
    props: FruitFindUniqueProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitFindUniqueResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitFindUniqueAction", "Fruit", "findUnique");
    return await FruitService.findUnique(props);
};

/**
 * ## Fruit Find Many (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const FruitFindManyAction = async <T extends Prisma.FruitFindManyArgs>(
    props: FruitFindManyProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitFindManyResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitFindManyAction", "Fruit", "findMany");
    return await FruitService.findMany(props);
};

/**
 * ## Fruit Count (Server Action)
 *
 * **WARNING**: Server actions can't be cached and parallelized
 *
 * - Do not use this for fetching data, use API routes with caching instead
 * - Use it to get fresh data, without any cache
 *
 *  **Note**: function generated from template.
 */
export const FruitCountAction = async <T extends Prisma.FruitCountArgs>(
    props: FruitCountProps<T>,
    // disableSafeMessage: boolean = false,
): Promise<FruitCountResponse<T>> => {
    // await requiresSafeMessage(disableSafeMessage, "FruitCountAction", "Fruit", "count");
    return await FruitService.count(props);
};
