import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import {
    BasketCountCached,
    BasketFindFirstCached,
    BasketFindManyCached,
    BasketFindUniqueCached,
} from "@services/cached";
import { decodeParams } from "@utils/url-parsers";
import { NextRequest, NextResponse } from "next/server";
import { ResponseFormat } from "@/solid/solid-config";

/**
 * # Basket Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type BasketFindFirstProps<T extends Prisma.BasketFindFirstArgs> = Prisma.SelectSubset<T, Prisma.BasketFindFirstArgs>;
type BasketFindFirstResponse<T extends Prisma.BasketFindFirstArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type BasketFindUniqueProps<T extends Prisma.BasketFindUniqueArgs> = Prisma.SelectSubset<T, Prisma.BasketFindUniqueArgs>;
type BasketFindUniqueResponse<T extends Prisma.BasketFindUniqueArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type BasketFindManyProps<T extends Prisma.BasketFindManyArgs> = Prisma.SelectSubset<T, Prisma.BasketFindManyArgs>;
type BasketFindManyResponse<T extends Prisma.BasketFindManyArgs> = GetResult<
    Prisma.$BasketPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type BasketCountProps<T extends Prisma.BasketCountArgs> = Prisma.SelectSubset<T, Prisma.BasketCountArgs>;
type BasketCountResponse<T extends Prisma.BasketCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.BasketCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type BasketRoutes<Input> = {
    "/solid/basket/findFirst": <T extends Prisma.BasketFindFirstArgs>() => {
        params: BasketFindFirstProps<T>;
        response: BasketFindFirstResponse<Input extends BasketFindFirstProps<T> ? Input : never>;
    };
    "/solid/basket/findUnique": <T extends Prisma.BasketFindUniqueArgs>() => {
        params: BasketFindUniqueProps<T>;
        response: BasketFindUniqueResponse<Input extends BasketFindUniqueProps<T> ? Input : never>;
    };
    "/solid/basket/findMany": <T extends Prisma.BasketFindManyArgs>() => {
        params: BasketFindManyProps<T>;
        response: BasketFindManyResponse<Input extends BasketFindManyProps<T> ? Input : never>;
    };
    "/solid/basket/count": <T extends Prisma.BasketCountArgs>() => {
        params: BasketCountProps<T>;
        response: BasketCountResponse<Input extends BasketCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const BasketFindFirstApi = async <T extends Prisma.BasketFindFirstArgs>(
    request: NextRequest,
): RouteResponse<BasketFindFirstResponse<T>> => {
    try {
        const params: BasketFindFirstProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: BasketFindFirstResponse<T> = await BasketFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const BasketFindUniqueApi = async <T extends Prisma.BasketFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<BasketFindUniqueResponse<T>> => {
    try {
        const params: BasketFindUniqueProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: BasketFindUniqueResponse<T> = await BasketFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const BasketFindManyApi = async <T extends Prisma.BasketFindManyArgs>(
    request: NextRequest,
): RouteResponse<BasketFindManyResponse<T>> => {
    try {
        const params: BasketFindManyProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: BasketFindManyResponse<T> = await BasketFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const BasketCountApi = async <T extends Prisma.BasketCountArgs>(
    request: NextRequest,
): RouteResponse<BasketCountResponse<T>> => {
    try {
        const params: BasketCountProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: BasketCountResponse<T> = await BasketCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
