import { Prisma } from "@prisma/client/client";
import { GetResult, InternalArgs, PrismaClientOptions } from "@prisma/client/runtime/client";
import {
    QuantityCountCached,
    QuantityFindFirstCached,
    QuantityFindManyCached,
    QuantityFindUniqueCached,
} from "@services/cached";
import { decodeParams } from "@utils/url-parsers";
import { NextRequest, NextResponse } from "next/server";
import { ResponseFormat } from "@/solid/solid-config";

/**
 * # Quantity Api Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/api/{{model}}Api.hbs` as base template
 * - to generate api function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

// ========== Types ========== //

// Find First
type QuantityFindFirstProps<T extends Prisma.QuantityFindFirstArgs> = Prisma.SelectSubset<
    T,
    Prisma.QuantityFindFirstArgs
>;
type QuantityFindFirstResponse<T extends Prisma.QuantityFindFirstArgs> = GetResult<
    Prisma.$QuantityPayload<InternalArgs>,
    T,
    "findFirst",
    PrismaClientOptions
>;

// Find Unique
type QuantityFindUniqueProps<T extends Prisma.QuantityFindUniqueArgs> = Prisma.SelectSubset<
    T,
    Prisma.QuantityFindUniqueArgs
>;
type QuantityFindUniqueResponse<T extends Prisma.QuantityFindUniqueArgs> = GetResult<
    Prisma.$QuantityPayload<InternalArgs>,
    T,
    "findUnique",
    PrismaClientOptions
>;

// Find Many
type QuantityFindManyProps<T extends Prisma.QuantityFindManyArgs> = Prisma.SelectSubset<T, Prisma.QuantityFindManyArgs>;
type QuantityFindManyResponse<T extends Prisma.QuantityFindManyArgs> = GetResult<
    Prisma.$QuantityPayload<InternalArgs>,
    T,
    "findMany",
    PrismaClientOptions
>;

// Count
type QuantityCountProps<T extends Prisma.QuantityCountArgs> = Prisma.SelectSubset<T, Prisma.QuantityCountArgs>;
type QuantityCountResponse<T extends Prisma.QuantityCountArgs> =
    // eslint-disable-next-line
    T extends { select: any }
        ? T["select"] extends true
            ? number
            : Prisma.GetScalarType<T["select"], Prisma.QuantityCountAggregateOutputType>
        : number;

// ========== Routes ========== //

type RouteResponse<T> = Promise<NextResponse<ResponseFormat<T>>>;

export type QuantityRoutes<Input> = {
    "/solid/quantity/findFirst": <T extends Prisma.QuantityFindFirstArgs>() => {
        params: QuantityFindFirstProps<T>;
        response: QuantityFindFirstResponse<Input extends QuantityFindFirstProps<T> ? Input : never>;
    };
    "/solid/quantity/findUnique": <T extends Prisma.QuantityFindUniqueArgs>() => {
        params: QuantityFindUniqueProps<T>;
        response: QuantityFindUniqueResponse<Input extends QuantityFindUniqueProps<T> ? Input : never>;
    };
    "/solid/quantity/findMany": <T extends Prisma.QuantityFindManyArgs>() => {
        params: QuantityFindManyProps<T>;
        response: QuantityFindManyResponse<Input extends QuantityFindManyProps<T> ? Input : never>;
    };
    "/solid/quantity/count": <T extends Prisma.QuantityCountArgs>() => {
        params: QuantityCountProps<T>;
        response: QuantityCountResponse<Input extends QuantityCountProps<T> ? Input : never>;
    };
};

// ========== Services ========== //

export const QuantityFindFirstApi = async <T extends Prisma.QuantityFindFirstArgs>(
    request: NextRequest,
): RouteResponse<QuantityFindFirstResponse<T>> => {
    try {
        const params: QuantityFindFirstProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: QuantityFindFirstResponse<T> = await QuantityFindFirstCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const QuantityFindUniqueApi = async <T extends Prisma.QuantityFindUniqueArgs>(
    request: NextRequest,
): RouteResponse<QuantityFindUniqueResponse<T>> => {
    try {
        const params: QuantityFindUniqueProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: QuantityFindUniqueResponse<T> = await QuantityFindUniqueCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const QuantityFindManyApi = async <T extends Prisma.QuantityFindManyArgs>(
    request: NextRequest,
): RouteResponse<QuantityFindManyResponse<T>> => {
    try {
        const params: QuantityFindManyProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: QuantityFindManyResponse<T> = await QuantityFindManyCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};

export const QuantityCountApi = async <T extends Prisma.QuantityCountArgs>(
    request: NextRequest,
): RouteResponse<QuantityCountResponse<T>> => {
    try {
        const params: QuantityCountProps<T> = decodeParams(request.nextUrl.searchParams);
        const response: QuantityCountResponse<T> = await QuantityCountCached(params);
        return NextResponse.json({ data: response }, { status: 200 });
    } catch (error) {
        return NextResponse.json({ error: (error as Error).message }, { status: 500 });
    }
};
