/**
 * Formatage de la sortie en fichier .env
 */
import type { OutputGroup, Settings } from "./types";

/**
 * Formate les groupes en contenu de fichier .env
 */
export function formatEnvFile(groups: OutputGroup[], env: string, settings: Settings): string {
    const envDescription = settings.envs[env] || "";

    const lines: string[] = [
        `# Generated by scripts/generate-env`,
        `# Environment: ${env}${envDescription ? ` - ${envDescription}` : ""}`,
        `# Do not edit manually - modify env/env.config.ts instead`,
        "",
    ];

    for (const group of groups) {
        lines.push(group.comment);

        for (const [key, entry] of Object.entries(group.vars)) {
            const formatted = formatEnvVar(key, entry.value);
            lines.push(entry.commented ? `# ${formatted}` : formatted);
        }

        lines.push("");
    }

    return lines.join("\n");
}

/**
 * Formate une variable d'environnement
 *
 * Ajoute des guillemets si la valeur contient des caractères spéciaux
 */
function formatEnvVar(key: string, value: string): string {
    const needsQuotes = /[\s"'()!]/.test(value);
    return `${key}=${needsQuotes ? `"${value}"` : value}`;
}
