import PrismaInstance from "@lib/prisma";
import { Prisma } from "@prisma/client/client";
import {
    BasketCountProps,
    BasketCountResponse,
    BasketCreateManyProps,
    BasketCreateManyResponse,
    BasketCreateProps,
    BasketCreateResponse,
    BasketDeleteManyProps,
    BasketDeleteManyResponse,
    BasketDeleteProps,
    BasketDeleteResponse,
    BasketFindFirstProps,
    BasketFindFirstResponse,
    BasketFindManyProps,
    BasketFindManyResponse,
    BasketFindUniqueProps,
    BasketFindUniqueResponse,
    BasketUpdateManyProps,
    BasketUpdateManyResponse,
    BasketUpdateProps,
    BasketUpdateResponse,
    BasketUpsertProps,
    BasketUpsertResponse,
} from "@services/types";

/**
 * # Basket Class Services
 *
 * This file:
 * - is generated by the command `pnpm run generate:all`
 * - that executes the script: `solid/solid-generator.ts`
 * - which uses `solid/templates/services/class/{{model}}Class.hbs` as base template
 * - to generate class function files for every models available in the `prisma/client/index.d.ts`.
 *
 * > **Warning**: Do not edit this file directly. Your changes will be lost the next time the code is generated.
 */

/**
 * ## Basket Class
 */
export default class BasketService {
    /**
     * ## Basket Create (Class)
     */
    static async create<T extends Prisma.BasketCreateArgs>(
        props: BasketCreateProps<T>,
    ): Promise<BasketCreateResponse<T>> {
        try {
            return await PrismaInstance.basket.create(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Upsert (Class)
     */
    static async upsert<T extends Prisma.BasketUpsertArgs>(
        props: BasketUpsertProps<T>,
    ): Promise<BasketUpsertResponse<T>> {
        try {
            return await PrismaInstance.basket.upsert(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Update (Class)
     */
    static async update<T extends Prisma.BasketUpdateArgs>(
        props: BasketUpdateProps<T>,
    ): Promise<BasketUpdateResponse<T>> {
        try {
            return await PrismaInstance.basket.update(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Delete (Class)
     */
    static async delete<T extends Prisma.BasketDeleteArgs>(
        props: BasketDeleteProps<T>,
    ): Promise<BasketDeleteResponse<T>> {
        try {
            return await PrismaInstance.basket.delete(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Create Many (Class)
     */
    static async createMany<T extends Prisma.BasketCreateManyArgs>(
        props: BasketCreateManyProps<T>,
    ): Promise<BasketCreateManyResponse> {
        try {
            return await PrismaInstance.basket.createMany(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Update Many (Class)
     */
    static async updateMany<T extends Prisma.BasketUpdateManyArgs>(
        props: BasketUpdateManyProps<T>,
    ): Promise<BasketUpdateManyResponse> {
        try {
            return await PrismaInstance.basket.updateMany(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Delete Many (Class)
     */
    static async deleteMany<T extends Prisma.BasketDeleteManyArgs>(
        props: BasketDeleteManyProps<T>,
    ): Promise<BasketDeleteManyResponse> {
        try {
            return await PrismaInstance.basket.deleteMany(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Find First (Class)
     */
    static async findFirst<T extends Prisma.BasketFindFirstArgs>(
        props: BasketFindFirstProps<T>,
    ): Promise<BasketFindFirstResponse<T>> {
        try {
            return await PrismaInstance.basket.findFirst(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Find Unique (Class)
     */
    static async findUnique<T extends Prisma.BasketFindUniqueArgs>(
        props: BasketFindUniqueProps<T>,
    ): Promise<BasketFindUniqueResponse<T>> {
        try {
            return await PrismaInstance.basket.findUnique(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Find Many (Class)
     */
    static async findMany<T extends Prisma.BasketFindManyArgs>(
        props: BasketFindManyProps<T>,
    ): Promise<BasketFindManyResponse<T>> {
        try {
            return await PrismaInstance.basket.findMany(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Basket Count (Class)
     */
    static async count<T extends Prisma.BasketCountArgs>(props: BasketCountProps<T>): Promise<BasketCountResponse<T>> {
        try {
            return await PrismaInstance.basket.count(props);
        } catch (error) {
            throw BasketService.error(error);
        }
    }

    /**
     * ## Error handling (Class)
     */
    private static async error(error: unknown): Promise<{ error: string }> {
        if (process.env.NODE_ENV === "development") {
            const message = (error as Error).message;
            console.error(message);
            throw new Error(message);
        }

        // TODO: add logging
        // await Logging(error);

        // Return safe error message to client
        throw new Error("Something went wrong...");
    }
}
