name: Checks Pipeline

on:
    pull_request:
        branches: [main, test]

jobs:
    commit:
        name: Commit Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: wagoid/commitlint-github-action@v6

    setup-base:
        name: Setup dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-base

    lint:
        name: Lint check
        runs-on: ubuntu-latest
        needs: [commit, setup-base]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-base
            - uses: ./.github/actions/quality-check
              with:
                  check-type: lint
    format:
        name: Format check
        runs-on: ubuntu-latest
        needs: [commit, setup-base]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-base
            - uses: ./.github/actions/quality-check
              with:
                  check-type: format
    type:
        name: Type check
        runs-on: ubuntu-latest
        needs: [commit, setup-base]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-base
            - uses: ./.github/actions/quality-check
              with:
                  check-type: type
